### PR TITLE
Rewrite in TypeScript, a.k.a. better.

### PR DESCRIPTION
**Pull request by NotReallyEight**

### CODE REVIEW

**Comment by DTrombett** [comment]
> a.k.a. better.

Cit.

**Comment by NotReallyEight** [comment]
:neutral_face:

**Comment by DTrombett** [comment]
You're so lazy that this PR will never be merged...

**Comment by NotReallyEight** [comment]
No spoiler

**Comment by NotReallyEight** [comment]
I completely forgot what I needed to do here

**Comment by NotReallyEight** [comment]
Nice

**Pull request closed without merging**
